const productData = [
	{
		id: 1,
		name: "Vapormax",
		price: 42200,
		img: "img/productos/nike/vapormax.png",
		modelo: "Vapormax",
		category: "remeras",
		description: "100%-algodon",
		envio: 2000,
	},
	{
		id: 2,
		name: "Airmax 97",
		price: 37600,
		img: "img/productos/nike/977.png",
		modelo: "Airmax 97",
		category: "remeras",
		description: "100%-algodon",
		envio: 2000,
	},
	{
		id: 3,
		name: "Airmax 95",
		price: 2200,
		img: "img/productos/nike/95.png",
		modelo: "Airmax 95",
		category: "remeras",
		description: "100%-algodon",
		envio: 2000,
	},
	{
		id: 4,
		name: "Jordan x Off-White",
		price: 50000,
		img: "img/productos/nike/offwhite.png",
		modelo: "Off-White",
		category: "remeras",
		description: "100%-algodon",
		envio: 2000,
	},
	{
		id: 5,
		name: "Superstar",
		price: 30000,
		img: "img/productos/adidas/superstar.png",
		modelo: "Superstar",
		category: "gorras",
		description: "Trucker",
		envio: 2000,
	},
	{
		id: 6,
		name: "Ozweego",
		price: 38800,
		img: "img/productos/adidas/ozweego.png",
		modelo: "Ozweego",
		category: "gorras",
		description: "Trucker",
		envio: 2000,
	},
	{
		id: 7,
		name: "Yeezy",
		price: 48000,
		img: "img/productos/adidas/yeezy.png",
		modelo: "Yeezy 350",
		category: "gorras",
		description: "Trucker",
		envio: 2000,
	},
	{
		id: 8,
		name: "Yeezy Boost 700",
		price: 49500,
		img: "img/productos/adidas/700.png",
		modelo: "Yeezy 700",
		category: "gorras",
		description: "Trucker",
		envio: 2000,
	},
	{
		id: 9,
		name: "574",
		price: 22500,
		img: "img/productos/NB/574.PNG",
		modelo: "574",
		category: "tazas",
		description: "Ceramica",
		envio: 2000,
	},
	{
		id: 10,
		name: "990",
		price: 26000,
		img: "img/productos/NB/990.PNG",
		modelo: "990",
		category: "tazas",
		description: "Ceramica",
		envio: 2000,
	},
	{
		id: 11,
		name: "Manteca",
		price: 34500,
		img: "img/productos/DC/manteca.png",
		category: "suplementos",
		description: "Proteina",
		modelo: "Manteca",
		envio: 2000,
	},
	{
		id: 12,
		name: "Court",
		price: 32000,
		img: "img/productos/DC/court.png",
		category: "suplementos",
		description: "Creatina",
		modelo: "Court",
		envio: 2000,
	},
	{
		id: 13,
		name: "Infinite",
		price: 4000,
		img: "img/productos/DC/infinite.png",
		category: "suplementos",
		description: "Aminoacidos",
		modelo: "Infinite",
		envio: 2000,
	},
	{
		id: 14,
		name: "Push/Pull/Legs",
		price: 4500,
		img: "img/productos/rutinas/rutina-1.jpg",
		duration: "4 meses",
		category: "rutinas",
		description: "Hipertrofia",
		envio: 0,
	},
	{
		id: 15,
		name: "PHAT",
		price: 4500,
		img: "img/productos/rutinas/rutina-2.jpg",
		duration: "4 meses",
		category: "rutinas",
		description: "Hipertrofia",
		envio: 0,
	},
	{
		id: 16,
		name: "Powerbuilding",
		price: 4500,
		img: "img/productos/rutinas/rutina-3.jpg",
		duration: "4 meses",
		category: "rutinas",
		description: "Hipertrofia/Fuerza",
		envio: 0,
	},
	{
		id: 17,
		name: "Upper/Lower",
		price: 4500,
		img: "img/productos/rutinas/rutina-4.jpg",
		duration: "4 meses",
		category: "rutinas",
		description: "Hipertrofia/Fuerza",
		envio: 0,
	},
	{
		id: 18,
		name: "Fullbody-Free",
		price: 0,
		img: "img/productos/rutinas/rutina-5.jpg",
		duration: "3 meses",
		category: "rutinas",
		description: "Hipertrofia",
		envio: 0,
	},
	{
		id: 19,
		name: "Upper/Lower-Free",
		price: 0,
		img: "img/productos/rutinas/rutina-6.jpg",
		duration: "3 meses",
		category: "rutinas",
		description: "Hipertrofia/Fuerza",
		envio: 0,
	},
	{
		id: 20,
		name: "Push/Pull-Free",
		price: 0,
		img: "img/productos/rutinas/rutina-7.jpg",
		duration: "3 meses",
		category: "rutinas",
		description: "Hipertrofia",
		envio: 0,
	},
];

